### ISSUE TITLE
Really interesting project! How do I build and run?

### ISSUE THREAD

**Issue by li-js** [29jm/Gravity-Simulation#1]
It is really an interesting project. How should I build and run it? 

The first obstacle I ran into when building the cpp source code is:
```
./Universe.hpp:4:10: fatal error: 'SFML/Graphics.hpp' file not found
```
Any advice is appreciated.

**Comment by 29jm** [comment]
Hi ! This project uses SFML2 for graphics/input, you'll need to install it first. If you're on Debian/Ubuntu it's the `libsfml-dev` package, otherwise check the SFML website for instructions. Then you should be able to run `make release` and be set :)  

Edit: you can then run it with `./gravity`.
